#!/usr/bin/env python3
from turtle import *

def ironMan():
        circle(50)
        right(90)
        forward(200)
        up()
        home()
        right(90)
        forward(50)
        down()
        right(45)
        forward(100)
        up()
        home()
        right(90)
        forward(50)
        left(45)
        down()
        forward(100)
        up()
        home()
        right(90)
        forward(200)
        right(45)
        down()
        forward(100)
        up()
        home()
        right(90)
        forward(200)
        left(45)
        down()
        forward(100)
        mainloop()

ironMan()
